version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    timezone: Europe/Copenhagen
  assignees:
  - arnested
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    timezone: Europe/Copenhagen
  assignees:
  - arnested
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    timezone: Europe/Copenhagen
  assignees:
  - arnested
